### Cadatrar endereço
POST http://127.0.0.1:8000/api/endereco/camila@gmail.com

{
    "nome": "Casa",
    "logradouro": "Rua Minha",
    "cep": "385652321",
    "bairro": "Bairro",
    "cidade": "Uberlandia",
    "estado": "Minas Gerais",
    "numero": "5000",
    "entrega": true

}

### Pesquisar endereço pelo email
GET http://127.0.0.1:8000/api/endereco/camila@gmail.com


### Deletar um endereço do cliente
DELETE  http://127.0.0.1:8000/api/clientes/camila@gmail.com